apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: vault-tls
  namespace: vault
spec:
  secretName: vault-tls
  dnsNames:
  - vault-ca.local
  issuerRef:
    name: selfsigning-issuer
    kind: ClusterIssuer
